#!/bin/sh

# SL10.0 *and* code10 (SL10.1, SLES10, SLED10)
if [ -e /etc/SuSE-release ]; then
    #grep -iq 'SUSE LINUX' /etc/SuSE-release
    #grep -iq 'VERSION *= *10' /etc/SuSE-release
    for new in \
        /opt/gnome/bin \
        /opt/kde*/bin
    do
        if [ -d "$new" ]; then
            PATH="$new:$PATH"
        fi
    done

    if [ -x /opt/gnome/bin/gtk-config ]; then
        export GTK_CONFIG=/opt/gnome/bin/gtk-config
    fi
fi
